version: '3.0'

services:
  grafana:
    container_name: 'sandstormmedia-nats-datasource'
    depends_on:
      - nats
    environment:
      GF_LOG_LEVEL: 'debug'
    build:
      context: ./.config
      args:
        grafana_version: ${GRAFANA_VERSION:-9.2.5}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/sandstormmedia-nats-datasource
      - ./provisioning:/etc/grafana/provisioning
  nats:
    container_name: nats
    ports:
      - '4222:4222'
    image: nats
