version: '3.0'

services:
  grafana:
    container_name: 'sandstormmedia-nats-datasource'
    depends_on:
      - nats
    environment:
      GF_LOG_LEVEL: 'debug'
    build:
      context: ./.config
      args:
        grafana_version: ${GRAFANA_VERSION:-9.2.5}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/sandstormmedia-nats-datasource
      # for auto-creating a dashboard and a datasource on startup
      - ./provisioning:/etc/grafana/provisioning
      - ./src/dashboards:/opt/grafana-dashboards
  nats:
    container_name: nats
    ports:
      - '4222:4222'
    image: nats:2.9.11
    command:
      - "-c"
      - /nats-server.conf
      - --name
      - nats
    volumes:
      - "./provisioning/nats-server.conf:/nats-server.conf"

  nats2:
    container_name: nats2
    ports:
      - '4223:4222'
    image: nats:2.9.11
    command:
      - "-c"
      - /nats-server.conf
      - --name
      - nats2
      - -routes
      - nats://nats:4248
    volumes:
      - "./provisioning/nats-server.conf:/nats-server.conf"
